---
ansible_port: 22
ansible_user: root
ansible_password: root

locale_timezone: "Asia/Tokyo"

#
# service
#
service_name_of_file: "icon-server"
service_port_of_file: 50101
service_exec_of_file: "jns-file-server"
