package main

import (
	"context"
	"fmt"
	"log"
	"net/http"

	"connectrpc.com/connect"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	filev1 "github.com/tappoy/jns/gen/file/v1"        // generated by protoc-gen-go
	"github.com/tappoy/jns/gen/file/v1/filev1connect" // generated by protoc-gen-connect-go
)

type FileServer struct{}

func (s *FileServer) File(
	ctx context.Context,
	req *connect.Request[filev1.FileRequest],
) (*connect.Response[filev1.FileResponse], error) {
	log.Println("Request headers: ", req.Header())
	res := connect.NewResponse(&filev1.FileResponse{
		Fileing: fmt.Sprintf("Hello, %s!", req.Msg.Name),
	})
	res.Header().Set("File-Version", "v1")
	return res, nil
}

func main() {
	fileer := &FileServer{}
	mux := http.NewServeMux()
	path, handler := filev1connect.NewFileServiceHandler(fileer)
	mux.Handle(path, handler)
	http.ListenAndServe(
		"localhost:8080",
		// Use h2c so we can serve HTTP/2 without TLS.
		h2c.NewHandler(mux, &http2.Server{}),
	)
}
