// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: file/v1/private.proto

package filev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PostFile
type PostFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DirPath string `protobuf:"bytes,1,opt,name=dir_path,json=dirPath,proto3" json:"dir_path,omitempty"`
	File    []byte `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *PostFileRequest) Reset() {
	*x = PostFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_v1_private_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostFileRequest) ProtoMessage() {}

func (x *PostFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_private_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostFileRequest.ProtoReflect.Descriptor instead.
func (*PostFileRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_private_proto_rawDescGZIP(), []int{0}
}

func (x *PostFileRequest) GetDirPath() string {
	if x != nil {
		return x.DirPath
	}
	return ""
}

func (x *PostFileRequest) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

type PostFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId string `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
}

func (x *PostFileResponse) Reset() {
	*x = PostFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_v1_private_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostFileResponse) ProtoMessage() {}

func (x *PostFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_private_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostFileResponse.ProtoReflect.Descriptor instead.
func (*PostFileResponse) Descriptor() ([]byte, []int) {
	return file_file_v1_private_proto_rawDescGZIP(), []int{1}
}

func (x *PostFileResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

// GCFile
type GCFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MarkedFile []string `protobuf:"bytes,1,rep,name=marked_file,json=markedFile,proto3" json:"marked_file,omitempty"`
}

func (x *GCFileRequest) Reset() {
	*x = GCFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_v1_private_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GCFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCFileRequest) ProtoMessage() {}

func (x *GCFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_private_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCFileRequest.ProtoReflect.Descriptor instead.
func (*GCFileRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_private_proto_rawDescGZIP(), []int{2}
}

func (x *GCFileRequest) GetMarkedFile() []string {
	if x != nil {
		return x.MarkedFile
	}
	return nil
}

type GCFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GCFileResponse) Reset() {
	*x = GCFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_v1_private_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GCFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCFileResponse) ProtoMessage() {}

func (x *GCFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_private_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCFileResponse.ProtoReflect.Descriptor instead.
func (*GCFileResponse) Descriptor() ([]byte, []int) {
	return file_file_v1_private_proto_rawDescGZIP(), []int{3}
}

// GCDir
type GCDirRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MarkedDir []string `protobuf:"bytes,1,rep,name=marked_dir,json=markedDir,proto3" json:"marked_dir,omitempty"`
}

func (x *GCDirRequest) Reset() {
	*x = GCDirRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_v1_private_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GCDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCDirRequest) ProtoMessage() {}

func (x *GCDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_private_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCDirRequest.ProtoReflect.Descriptor instead.
func (*GCDirRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_private_proto_rawDescGZIP(), []int{4}
}

func (x *GCDirRequest) GetMarkedDir() []string {
	if x != nil {
		return x.MarkedDir
	}
	return nil
}

type GCDirResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GCDirResponse) Reset() {
	*x = GCDirResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_v1_private_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GCDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCDirResponse) ProtoMessage() {}

func (x *GCDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_private_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCDirResponse.ProtoReflect.Descriptor instead.
func (*GCDirResponse) Descriptor() ([]byte, []int) {
	return file_file_v1_private_proto_rawDescGZIP(), []int{5}
}

// Vacuum
type VacuumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VacuumRequest) Reset() {
	*x = VacuumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_v1_private_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VacuumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VacuumRequest) ProtoMessage() {}

func (x *VacuumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_private_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VacuumRequest.ProtoReflect.Descriptor instead.
func (*VacuumRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_private_proto_rawDescGZIP(), []int{6}
}

type VacuumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VacuumResponse) Reset() {
	*x = VacuumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_v1_private_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VacuumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VacuumResponse) ProtoMessage() {}

func (x *VacuumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_private_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VacuumResponse.ProtoReflect.Descriptor instead.
func (*VacuumResponse) Descriptor() ([]byte, []int) {
	return file_file_v1_private_proto_rawDescGZIP(), []int{7}
}

var File_file_v1_private_proto protoreflect.FileDescriptor

var file_file_v1_private_proto_rawDesc = []byte{
	0x0a, 0x15, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31,
	0x22, 0x40, 0x0a, 0x0f, 0x50, 0x6f, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x69, 0x72, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x69, 0x72, 0x50, 0x61, 0x74, 0x68, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x69,
	0x6c, 0x65, 0x22, 0x2b, 0x0a, 0x10, 0x50, 0x6f, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x22,
	0x30, 0x0a, 0x0d, 0x47, 0x43, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x46, 0x69, 0x6c,
	0x65, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x43, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x2d, 0x0a, 0x0c, 0x47, 0x43, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x5f, 0x64, 0x69,
	0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x44,
	0x69, 0x72, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x43, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x56, 0x61, 0x63, 0x75, 0x75, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x56, 0x61, 0x63, 0x75, 0x75, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x8b, 0x02, 0x0a, 0x12, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a,
	0x08, 0x50, 0x6f, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x2e, 0x66, 0x69, 0x6c, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f,
	0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x3b, 0x0a, 0x06, 0x47, 0x43, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x16, 0x2e, 0x66, 0x69, 0x6c,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x43, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x43, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a,
	0x05, 0x47, 0x43, 0x44, 0x69, 0x72, 0x12, 0x15, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x43, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x43, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x06, 0x56, 0x61, 0x63, 0x75, 0x75,
	0x6d, 0x12, 0x16, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x63, 0x75,
	0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x66, 0x69, 0x6c, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x63, 0x75, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x70, 0x70, 0x6f, 0x79, 0x2f, 0x6a, 0x6e, 0x73, 0x2f, 0x67, 0x6f,
	0x2f, 0x5f, 0x62, 0x75, 0x66, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x66, 0x69,
	0x6c, 0x65, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_file_v1_private_proto_rawDescOnce sync.Once
	file_file_v1_private_proto_rawDescData = file_file_v1_private_proto_rawDesc
)

func file_file_v1_private_proto_rawDescGZIP() []byte {
	file_file_v1_private_proto_rawDescOnce.Do(func() {
		file_file_v1_private_proto_rawDescData = protoimpl.X.CompressGZIP(file_file_v1_private_proto_rawDescData)
	})
	return file_file_v1_private_proto_rawDescData
}

var file_file_v1_private_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_file_v1_private_proto_goTypes = []any{
	(*PostFileRequest)(nil),  // 0: file.v1.PostFileRequest
	(*PostFileResponse)(nil), // 1: file.v1.PostFileResponse
	(*GCFileRequest)(nil),    // 2: file.v1.GCFileRequest
	(*GCFileResponse)(nil),   // 3: file.v1.GCFileResponse
	(*GCDirRequest)(nil),     // 4: file.v1.GCDirRequest
	(*GCDirResponse)(nil),    // 5: file.v1.GCDirResponse
	(*VacuumRequest)(nil),    // 6: file.v1.VacuumRequest
	(*VacuumResponse)(nil),   // 7: file.v1.VacuumResponse
}
var file_file_v1_private_proto_depIdxs = []int32{
	0, // 0: file.v1.PrivateFileService.PostFile:input_type -> file.v1.PostFileRequest
	2, // 1: file.v1.PrivateFileService.GCFile:input_type -> file.v1.GCFileRequest
	4, // 2: file.v1.PrivateFileService.GCDir:input_type -> file.v1.GCDirRequest
	6, // 3: file.v1.PrivateFileService.Vacuum:input_type -> file.v1.VacuumRequest
	1, // 4: file.v1.PrivateFileService.PostFile:output_type -> file.v1.PostFileResponse
	3, // 5: file.v1.PrivateFileService.GCFile:output_type -> file.v1.GCFileResponse
	5, // 6: file.v1.PrivateFileService.GCDir:output_type -> file.v1.GCDirResponse
	7, // 7: file.v1.PrivateFileService.Vacuum:output_type -> file.v1.VacuumResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_v1_private_proto_init() }
func file_file_v1_private_proto_init() {
	if File_file_v1_private_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_file_v1_private_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PostFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_v1_private_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PostFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_v1_private_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GCFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_v1_private_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GCFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_v1_private_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GCDirRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_v1_private_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GCDirResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_v1_private_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*VacuumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_v1_private_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*VacuumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_file_v1_private_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_v1_private_proto_goTypes,
		DependencyIndexes: file_file_v1_private_proto_depIdxs,
		MessageInfos:      file_file_v1_private_proto_msgTypes,
	}.Build()
	File_file_v1_private_proto = out.File
	file_file_v1_private_proto_rawDesc = nil
	file_file_v1_private_proto_goTypes = nil
	file_file_v1_private_proto_depIdxs = nil
}
