---
- name: Install the service command by go install
  command: "go install github.com/tappoy/jns/go/cmd/{{ service_cmd }}@develop"

- name: Make alias
  when: service_cmd != service_name
  file:
    src: "/root/go/bin/{{ service_cmd }}"
    dest: "/root/go/bin/{{ service_name }}"
    state: link

- name: Put service.env
  template:
    src: ./systemd/service.env
    dest: "/root/service.env"

- name: Put service
  template:
    src: ./systemd/simple_service_template.service
    dest: "/root/{{ service_name }}.service"

- name: Symlink service to /etc/systemd/system
  file:
    src: "/root/{{ service_name }}.service"
    dest: "/etc/systemd/system/{{ service_name }}.service"
    state: link

- name: "Create /srv/jns/{{ service_name }} if it does not exist"
  file:
    path: "/srv/jns/{{ service_name }}"
    state: directory
    mode: '0755'

- name: "Create /var/log/jns/{{ service_name }} if it does not exist"
  file:
    path: "/var/log/jns/{{ service_name }}"
    state: directory
    mode: '0755'

- name: Enable service and ensure it is not masked
  systemd_service:
    name: "{{ service_name }}"
    enabled: true
    masked: no

- name: Restart the service
  systemd_service:
    daemon_reload: true
    state: restarted
    name: "{{ service_name }}"
