---
- name: Install the service by go install
  when: service_exec is undefined
  command: "go install github.com/tappoy/jns/cmd/{{ service_name }}@latest"

- name: Make alias
  when: service_exec is defined
  file:
    src: "/root/go/bin/{{ service_exec }}"
    dest: "/root/go/bin/{{ service_name }}"
    state: link

- name: Copy simple_service_template.service
  copy:
    src: ./systemd/simple_service_template.service
    dest: "/root/{{ service_name }}.service"

- name: Replace SERVICE_NAME
  replace:
    path: "/root/{{ service_name }}.service"
    regexp: SERVICE_NAME
    replace: "{{ service_name }}"

- name: Replace SERVICE_PORT
  replace:
    path: "/root/{{ service_name }}.service"
    regexp: SERVICE_PORT
    replace: "{{ service_port }}"

- name: Symlink service to /etc/systemd/system
  file:
    src: "/root/{{ service_name }}.service"
    dest: "/etc/systemd/system/{{ service_name }}.service"
    state: link

- name: "Create /srv/{{ service_name }} if it does not exist"
  file:
    path: "/srv/{{ service_name }}"
    state: directory
    mode: '0755'

- name: "Create /log/{{ service_name }} if it does not exist"
  file:
    path: "/log/{{ service_name }}"
    state: directory
    mode: '0755'

- name: Enable service and ensure it is not masked
  systemd_service:
    name: "{{ service_name }}"
    enabled: true
    masked: no

- name: Make sure a service unit is running
  systemd_service:
    state: started
    name: "{{ service_name }}"
