---
- name: Setup
  hosts: all

  tasks:
  - name: set timezone
    community.general.timezone:
      name: "{{ locale_timezone }}"

  - name: install go
    community.general.pacman:
      name: go
      state: present

  - name: Run the equivalent of "pacman -Syu" as a separate step
    community.general.pacman:
      update_cache: true
      upgrade: true
