---
- name: Setup
  hosts: all

  tasks:
  - name: Set timezone
    timezone:
      name: "{{ locale_timezone }}"

  - name: Install go
    pacman:
      name: go
      state: present

  - name: Run the equivalent of "pacman -Syu" as a separate step
    pacman:
      update_cache: true
      upgrade: true
